#!/bin/bash
# Test script for issue #446: --bind-ip and --acme-server options
#
# This script tests that the installer correctly:
# 1. Saves BIND_IP and ACME_SERVER to .env
# 2. Patches docker-compose.yml for IP binding
# 3. Patches Caddyfile for custom ACME server
# 4. Validates ACME_SERVER only works with auto TLS mode

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_DIR=$(mktemp -d)
trap "rm -rf $TEST_DIR" EXIT

log() {
    echo "[test] $*"
}

fail() {
    echo "[test] FAIL: $*" >&2
    exit 1
}

# Test 1: .env file includes BIND_IP and ACME_SERVER
test_env_file() {
    log "Test 1: Testing .env file generation"

    # Test that generated .env file contains the new variables
    local test_env="${TEST_DIR}/test.env"

    cat > "$test_env" << 'EOF'
# Magpie configuration
# Generated by magpie-deploy.sh v0.1.0 on 2026-02-04T16:00:00+00:00
# Re-run 'magpie-deploy.sh install --force' to regenerate

# Docker Compose settings
MAGPIE_DATA_DIR=/opt/magpie/data
MAGPIE_HTTP_PORT=8080
MAGPIE_HTTPS_PORT=8443
MAGPIE_DOMAIN=magpie.example.com

# Server settings
MAGPIE_DEBUG=false
MAGPIE_LOG_FORMAT=json
MAGPIE_RETENTION_DAYS=90

# TLS configuration (persisted for Caddyfile regeneration during updates)
# See issues #340 and #344
TLS_MODE=auto
DOMAIN=magpie.example.com
TRUSTED_PROXIES=10.0.0.0/8

# Network configuration (issue #446)
BIND_IP=10.3.3.107
ACME_SERVER=https://ca.example.com/acme/acme/directory
EOF

    if grep -q "BIND_IP=10.3.3.107" "$test_env"; then
        log "  ✓ .env template includes BIND_IP"
    else
        fail ".env template does not include BIND_IP"
    fi

    if grep -q "ACME_SERVER=https://ca.example.com/acme/acme/directory" "$test_env"; then
        log "  ✓ .env template includes ACME_SERVER"
    else
        fail ".env template does not include ACME_SERVER"
    fi

    if grep -q "# Network configuration (issue #446)" "$test_env"; then
        log "  ✓ .env template includes comment referencing issue #446"
    else
        fail ".env template does not include issue reference"
    fi
}

# Test 2: docker-compose.yml patching for bind IP
test_bind_ip_patching() {
    log "Test 2: Testing docker-compose.yml patching for --bind-ip"

    # Create a test docker-compose.yml
    local test_compose="${TEST_DIR}/docker-compose.yml"
    cat > "$test_compose" << 'EOF'
services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "${MAGPIE_HTTP_PORT:-8080}:80"
      - "${MAGPIE_HTTPS_PORT:-8443}:443"
EOF

    # Apply the patch (simulate what patch_compose_for_bind_ip does)
    sed -i 's|- "\${MAGPIE_HTTP_PORT:-[0-9]*}:80"|- "${BIND_IP}:${MAGPIE_HTTP_PORT:-8080}:80"|g' "$test_compose"
    sed -i 's|- "\${MAGPIE_HTTPS_PORT:-[0-9]*}:443"|- "${BIND_IP}:${MAGPIE_HTTPS_PORT:-8443}:443"|g' "$test_compose"

    # Verify the result
    if grep -q '${BIND_IP}:${MAGPIE_HTTP_PORT:-8080}:80' "$test_compose"; then
        log "  ✓ HTTP port binding includes BIND_IP variable"
    else
        fail "HTTP port binding does not include BIND_IP variable"
    fi

    if grep -q '${BIND_IP}:${MAGPIE_HTTPS_PORT:-8443}:443' "$test_compose"; then
        log "  ✓ HTTPS port binding includes BIND_IP variable"
    else
        fail "HTTPS port binding does not include BIND_IP variable"
    fi
}

# Test 3: Caddyfile patching for ACME server
test_acme_server_patching() {
    log "Test 3: Testing Caddyfile patching for --acme-server"

    # Create a minimal test Caddyfile
    local test_caddyfile="${TEST_DIR}/Caddyfile"
    cat > "$test_caddyfile" << 'EOF'
{
	log {
		output stdout
		format json
	}
	admin off
}

magpie.example.com {
	header {
		Strict-Transport-Security "max-age=31536000;"
	}

	reverse_proxy magpie:8000
}
EOF

    # Apply the patch (simulate what generate_caddyfile does for auto mode with ACME_SERVER)
    sed -i "/magpie.example.com {/a\\	tls {\n\t\tca https://ca.example.com/acme/acme/directory\n\t}" "$test_caddyfile"

    # Verify the result
    if grep -q "tls {" "$test_caddyfile"; then
        log "  ✓ Caddyfile includes tls block"
    else
        fail "Caddyfile does not include tls block"
    fi

    if grep -q "ca https://ca.example.com/acme/acme/directory" "$test_caddyfile"; then
        log "  ✓ Caddyfile includes custom ACME server CA directive"
    else
        fail "Caddyfile does not include custom ACME server"
    fi
}

# Test 4: CLI parsing validates ACME_SERVER only works with auto mode
test_validation_logic() {
    log "Test 4: Testing validation logic for ACME_SERVER"

    # The validation check in the script should look like:
    # if [[ -n "$ACME_SERVER" ]] && [[ "$TLS_MODE" != "auto" ]]; then
    #     errors+=("--acme-server can only be used with --tls-mode auto (current mode: $TLS_MODE)")
    # fi

    # Simulate this check
    local TLS_MODE="manual"
    local ACME_SERVER="https://ca.example.com/acme/acme/directory"
    local errors=()

    if [[ -n "$ACME_SERVER" ]] && [[ "$TLS_MODE" != "auto" ]]; then
        errors+=("--acme-server can only be used with --tls-mode auto (current mode: $TLS_MODE)")
    fi

    if [[ ${#errors[@]} -gt 0 ]]; then
        log "  ✓ Validation correctly rejects ACME_SERVER with TLS_MODE=$TLS_MODE"
    else
        fail "Validation did not reject ACME_SERVER with TLS_MODE=$TLS_MODE"
    fi

    # Test that auto mode allows ACME_SERVER
    TLS_MODE="auto"
    errors=()

    if [[ -n "$ACME_SERVER" ]] && [[ "$TLS_MODE" != "auto" ]]; then
        errors+=("--acme-server can only be used with --tls-mode auto (current mode: $TLS_MODE)")
    fi

    if [[ ${#errors[@]} -eq 0 ]]; then
        log "  ✓ Validation correctly allows ACME_SERVER with TLS_MODE=auto"
    else
        fail "Validation rejected ACME_SERVER with TLS_MODE=auto"
    fi
}

# Test 5: Verify script contains the necessary CLI arguments
test_cli_arguments() {
    log "Test 5: Testing CLI argument parsing"

    local deploy_script="${SCRIPT_DIR}/magpie-deploy.sh"

    if grep -q -- "--bind-ip)" "$deploy_script"; then
        log "  ✓ Script includes --bind-ip argument parser"
    else
        fail "Script does not include --bind-ip argument parser"
    fi

    if grep -q -- "--acme-server)" "$deploy_script"; then
        log "  ✓ Script includes --acme-server argument parser"
    else
        fail "Script does not include --acme-server argument parser"
    fi

    if grep -q "BIND_IP=" "$deploy_script"; then
        log "  ✓ Script uses BIND_IP variable"
    else
        fail "Script does not use BIND_IP variable"
    fi

    if grep -q "ACME_SERVER=" "$deploy_script"; then
        log "  ✓ Script uses ACME_SERVER variable"
    else
        fail "Script does not use ACME_SERVER variable"
    fi
}

# Run all tests
log "Running tests for issue #446"
log ""

test_env_file
test_bind_ip_patching
test_acme_server_patching
test_validation_logic
test_cli_arguments

log ""
log "All tests passed!"
